// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: opentelemetry/proto/collector/trace/v1/trace_service.proto
// Protobuf C++ Version: 5.26.1

#ifndef GOOGLE_PROTOBUF_INCLUDED_opentelemetry_2fproto_2fcollector_2ftrace_2fv1_2ftrace_5fservice_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_opentelemetry_2fproto_2fcollector_2ftrace_2fv1_2ftrace_5fservice_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION != 5026001
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "opentelemetry/proto/trace/v1/trace.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_opentelemetry_2fproto_2fcollector_2ftrace_2fv1_2ftrace_5fservice_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_opentelemetry_2fproto_2fcollector_2ftrace_2fv1_2ftrace_5fservice_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_opentelemetry_2fproto_2fcollector_2ftrace_2fv1_2ftrace_5fservice_2eproto;
namespace opentelemetry {
namespace proto {
namespace collector {
namespace trace {
namespace v1 {
class ExportTracePartialSuccess;
struct ExportTracePartialSuccessDefaultTypeInternal;
extern ExportTracePartialSuccessDefaultTypeInternal _ExportTracePartialSuccess_default_instance_;
class ExportTraceServiceRequest;
struct ExportTraceServiceRequestDefaultTypeInternal;
extern ExportTraceServiceRequestDefaultTypeInternal _ExportTraceServiceRequest_default_instance_;
class ExportTraceServiceResponse;
struct ExportTraceServiceResponseDefaultTypeInternal;
extern ExportTraceServiceResponseDefaultTypeInternal _ExportTraceServiceResponse_default_instance_;
}  // namespace v1
}  // namespace trace
}  // namespace collector
}  // namespace proto
}  // namespace opentelemetry
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace opentelemetry {
namespace proto {
namespace collector {
namespace trace {
namespace v1 {

// ===================================================================


// -------------------------------------------------------------------

class ExportTracePartialSuccess final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:opentelemetry.proto.collector.trace.v1.ExportTracePartialSuccess) */ {
 public:
  inline ExportTracePartialSuccess() : ExportTracePartialSuccess(nullptr) {}
  ~ExportTracePartialSuccess() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ExportTracePartialSuccess(
      ::google::protobuf::internal::ConstantInitialized);

  inline ExportTracePartialSuccess(const ExportTracePartialSuccess& from) : ExportTracePartialSuccess(nullptr, from) {}
  inline ExportTracePartialSuccess(ExportTracePartialSuccess&& from) noexcept
      : ExportTracePartialSuccess(nullptr, std::move(from)) {}
  inline ExportTracePartialSuccess& operator=(const ExportTracePartialSuccess& from) {
    CopyFrom(from);
    return *this;
  }
  inline ExportTracePartialSuccess& operator=(ExportTracePartialSuccess&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ExportTracePartialSuccess& default_instance() {
    return *internal_default_instance();
  }
  static inline const ExportTracePartialSuccess* internal_default_instance() {
    return reinterpret_cast<const ExportTracePartialSuccess*>(
        &_ExportTracePartialSuccess_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(ExportTracePartialSuccess& a, ExportTracePartialSuccess& b) { a.Swap(&b); }
  inline void Swap(ExportTracePartialSuccess* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ExportTracePartialSuccess* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ExportTracePartialSuccess* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<ExportTracePartialSuccess>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ExportTracePartialSuccess& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ExportTracePartialSuccess& from) { ExportTracePartialSuccess::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ExportTracePartialSuccess* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "opentelemetry.proto.collector.trace.v1.ExportTracePartialSuccess"; }

 protected:
  explicit ExportTracePartialSuccess(::google::protobuf::Arena* arena);
  ExportTracePartialSuccess(::google::protobuf::Arena* arena, const ExportTracePartialSuccess& from);
  ExportTracePartialSuccess(::google::protobuf::Arena* arena, ExportTracePartialSuccess&& from) noexcept
      : ExportTracePartialSuccess(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kErrorMessageFieldNumber = 2,
    kRejectedSpansFieldNumber = 1,
  };
  // string error_message = 2;
  void clear_error_message() ;
  const std::string& error_message() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_error_message(Arg_&& arg, Args_... args);
  std::string* mutable_error_message();
  PROTOBUF_NODISCARD std::string* release_error_message();
  void set_allocated_error_message(std::string* value);

  private:
  const std::string& _internal_error_message() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_error_message(
      const std::string& value);
  std::string* _internal_mutable_error_message();

  public:
  // int64 rejected_spans = 1;
  void clear_rejected_spans() ;
  ::int64_t rejected_spans() const;
  void set_rejected_spans(::int64_t value);

  private:
  ::int64_t _internal_rejected_spans() const;
  void _internal_set_rejected_spans(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:opentelemetry.proto.collector.trace.v1.ExportTracePartialSuccess)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      86, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::ArenaStringPtr error_message_;
    ::int64_t rejected_spans_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_opentelemetry_2fproto_2fcollector_2ftrace_2fv1_2ftrace_5fservice_2eproto;
};
// -------------------------------------------------------------------

class ExportTraceServiceResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse) */ {
 public:
  inline ExportTraceServiceResponse() : ExportTraceServiceResponse(nullptr) {}
  ~ExportTraceServiceResponse() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ExportTraceServiceResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline ExportTraceServiceResponse(const ExportTraceServiceResponse& from) : ExportTraceServiceResponse(nullptr, from) {}
  inline ExportTraceServiceResponse(ExportTraceServiceResponse&& from) noexcept
      : ExportTraceServiceResponse(nullptr, std::move(from)) {}
  inline ExportTraceServiceResponse& operator=(const ExportTraceServiceResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline ExportTraceServiceResponse& operator=(ExportTraceServiceResponse&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ExportTraceServiceResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const ExportTraceServiceResponse* internal_default_instance() {
    return reinterpret_cast<const ExportTraceServiceResponse*>(
        &_ExportTraceServiceResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(ExportTraceServiceResponse& a, ExportTraceServiceResponse& b) { a.Swap(&b); }
  inline void Swap(ExportTraceServiceResponse* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ExportTraceServiceResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ExportTraceServiceResponse* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<ExportTraceServiceResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ExportTraceServiceResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ExportTraceServiceResponse& from) { ExportTraceServiceResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ExportTraceServiceResponse* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse"; }

 protected:
  explicit ExportTraceServiceResponse(::google::protobuf::Arena* arena);
  ExportTraceServiceResponse(::google::protobuf::Arena* arena, const ExportTraceServiceResponse& from);
  ExportTraceServiceResponse(::google::protobuf::Arena* arena, ExportTraceServiceResponse&& from) noexcept
      : ExportTraceServiceResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPartialSuccessFieldNumber = 1,
  };
  // .opentelemetry.proto.collector.trace.v1.ExportTracePartialSuccess partial_success = 1;
  bool has_partial_success() const;
  void clear_partial_success() ;
  const ::opentelemetry::proto::collector::trace::v1::ExportTracePartialSuccess& partial_success() const;
  PROTOBUF_NODISCARD ::opentelemetry::proto::collector::trace::v1::ExportTracePartialSuccess* release_partial_success();
  ::opentelemetry::proto::collector::trace::v1::ExportTracePartialSuccess* mutable_partial_success();
  void set_allocated_partial_success(::opentelemetry::proto::collector::trace::v1::ExportTracePartialSuccess* value);
  void unsafe_arena_set_allocated_partial_success(::opentelemetry::proto::collector::trace::v1::ExportTracePartialSuccess* value);
  ::opentelemetry::proto::collector::trace::v1::ExportTracePartialSuccess* unsafe_arena_release_partial_success();

  private:
  const ::opentelemetry::proto::collector::trace::v1::ExportTracePartialSuccess& _internal_partial_success() const;
  ::opentelemetry::proto::collector::trace::v1::ExportTracePartialSuccess* _internal_mutable_partial_success();

  public:
  // @@protoc_insertion_point(class_scope:opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::opentelemetry::proto::collector::trace::v1::ExportTracePartialSuccess* partial_success_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_opentelemetry_2fproto_2fcollector_2ftrace_2fv1_2ftrace_5fservice_2eproto;
};
// -------------------------------------------------------------------

class ExportTraceServiceRequest final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest) */ {
 public:
  inline ExportTraceServiceRequest() : ExportTraceServiceRequest(nullptr) {}
  ~ExportTraceServiceRequest() override;
  template <typename = void>
  explicit PROTOBUF_CONSTEXPR ExportTraceServiceRequest(
      ::google::protobuf::internal::ConstantInitialized);

  inline ExportTraceServiceRequest(const ExportTraceServiceRequest& from) : ExportTraceServiceRequest(nullptr, from) {}
  inline ExportTraceServiceRequest(ExportTraceServiceRequest&& from) noexcept
      : ExportTraceServiceRequest(nullptr, std::move(from)) {}
  inline ExportTraceServiceRequest& operator=(const ExportTraceServiceRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline ExportTraceServiceRequest& operator=(ExportTraceServiceRequest&& from) noexcept {
    if (this == &from) return *this;
    if (GetArena() == from.GetArena()
#ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetArena() != nullptr
#endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ExportTraceServiceRequest& default_instance() {
    return *internal_default_instance();
  }
  static inline const ExportTraceServiceRequest* internal_default_instance() {
    return reinterpret_cast<const ExportTraceServiceRequest*>(
        &_ExportTraceServiceRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(ExportTraceServiceRequest& a, ExportTraceServiceRequest& b) { a.Swap(&b); }
  inline void Swap(ExportTraceServiceRequest* other) {
    if (other == this) return;
#ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() != nullptr && GetArena() == other->GetArena()) {
#else   // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetArena() == other->GetArena()) {
#endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ExportTraceServiceRequest* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ExportTraceServiceRequest* New(::google::protobuf::Arena* arena = nullptr) const final {
    return ::google::protobuf::Message::DefaultConstruct<ExportTraceServiceRequest>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const ExportTraceServiceRequest& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const ExportTraceServiceRequest& from) { ExportTraceServiceRequest::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void InternalSwap(ExportTraceServiceRequest* other);
 private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() { return "opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest"; }

 protected:
  explicit ExportTraceServiceRequest(::google::protobuf::Arena* arena);
  ExportTraceServiceRequest(::google::protobuf::Arena* arena, const ExportTraceServiceRequest& from);
  ExportTraceServiceRequest(::google::protobuf::Arena* arena, ExportTraceServiceRequest&& from) noexcept
      : ExportTraceServiceRequest(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::MessageLite::ClassData* GetClassData()
      const final;

 public:
  ::google::protobuf::Metadata GetMetadata() const final;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kResourceSpansFieldNumber = 1,
  };
  // repeated .opentelemetry.proto.trace.v1.ResourceSpans resource_spans = 1;
  int resource_spans_size() const;
  private:
  int _internal_resource_spans_size() const;

  public:
  void clear_resource_spans() ;
  ::opentelemetry::proto::trace::v1::ResourceSpans* mutable_resource_spans(int index);
  ::google::protobuf::RepeatedPtrField<::opentelemetry::proto::trace::v1::ResourceSpans>* mutable_resource_spans();

  private:
  const ::google::protobuf::RepeatedPtrField<::opentelemetry::proto::trace::v1::ResourceSpans>& _internal_resource_spans() const;
  ::google::protobuf::RepeatedPtrField<::opentelemetry::proto::trace::v1::ResourceSpans>* _internal_mutable_resource_spans();
  public:
  const ::opentelemetry::proto::trace::v1::ResourceSpans& resource_spans(int index) const;
  ::opentelemetry::proto::trace::v1::ResourceSpans* add_resource_spans();
  const ::google::protobuf::RepeatedPtrField<::opentelemetry::proto::trace::v1::ResourceSpans>& resource_spans() const;
  // @@protoc_insertion_point(class_scope:opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 1,
      0, 2>
      _table_;
  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from);
    ::google::protobuf::RepeatedPtrField< ::opentelemetry::proto::trace::v1::ResourceSpans > resource_spans_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_opentelemetry_2fproto_2fcollector_2ftrace_2fv1_2ftrace_5fservice_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// ExportTraceServiceRequest

// repeated .opentelemetry.proto.trace.v1.ResourceSpans resource_spans = 1;
inline int ExportTraceServiceRequest::_internal_resource_spans_size() const {
  return _internal_resource_spans().size();
}
inline int ExportTraceServiceRequest::resource_spans_size() const {
  return _internal_resource_spans_size();
}
inline ::opentelemetry::proto::trace::v1::ResourceSpans* ExportTraceServiceRequest::mutable_resource_spans(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest.resource_spans)
  return _internal_mutable_resource_spans()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::opentelemetry::proto::trace::v1::ResourceSpans>* ExportTraceServiceRequest::mutable_resource_spans()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest.resource_spans)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_resource_spans();
}
inline const ::opentelemetry::proto::trace::v1::ResourceSpans& ExportTraceServiceRequest::resource_spans(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest.resource_spans)
  return _internal_resource_spans().Get(index);
}
inline ::opentelemetry::proto::trace::v1::ResourceSpans* ExportTraceServiceRequest::add_resource_spans() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::opentelemetry::proto::trace::v1::ResourceSpans* _add = _internal_mutable_resource_spans()->Add();
  // @@protoc_insertion_point(field_add:opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest.resource_spans)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::opentelemetry::proto::trace::v1::ResourceSpans>& ExportTraceServiceRequest::resource_spans() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:opentelemetry.proto.collector.trace.v1.ExportTraceServiceRequest.resource_spans)
  return _internal_resource_spans();
}
inline const ::google::protobuf::RepeatedPtrField<::opentelemetry::proto::trace::v1::ResourceSpans>&
ExportTraceServiceRequest::_internal_resource_spans() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.resource_spans_;
}
inline ::google::protobuf::RepeatedPtrField<::opentelemetry::proto::trace::v1::ResourceSpans>*
ExportTraceServiceRequest::_internal_mutable_resource_spans() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.resource_spans_;
}

// -------------------------------------------------------------------

// ExportTraceServiceResponse

// .opentelemetry.proto.collector.trace.v1.ExportTracePartialSuccess partial_success = 1;
inline bool ExportTraceServiceResponse::has_partial_success() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.partial_success_ != nullptr);
  return value;
}
inline void ExportTraceServiceResponse::clear_partial_success() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.partial_success_ != nullptr) _impl_.partial_success_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::opentelemetry::proto::collector::trace::v1::ExportTracePartialSuccess& ExportTraceServiceResponse::_internal_partial_success() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::opentelemetry::proto::collector::trace::v1::ExportTracePartialSuccess* p = _impl_.partial_success_;
  return p != nullptr ? *p : reinterpret_cast<const ::opentelemetry::proto::collector::trace::v1::ExportTracePartialSuccess&>(::opentelemetry::proto::collector::trace::v1::_ExportTracePartialSuccess_default_instance_);
}
inline const ::opentelemetry::proto::collector::trace::v1::ExportTracePartialSuccess& ExportTraceServiceResponse::partial_success() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse.partial_success)
  return _internal_partial_success();
}
inline void ExportTraceServiceResponse::unsafe_arena_set_allocated_partial_success(::opentelemetry::proto::collector::trace::v1::ExportTracePartialSuccess* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.partial_success_);
  }
  _impl_.partial_success_ = reinterpret_cast<::opentelemetry::proto::collector::trace::v1::ExportTracePartialSuccess*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse.partial_success)
}
inline ::opentelemetry::proto::collector::trace::v1::ExportTracePartialSuccess* ExportTraceServiceResponse::release_partial_success() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::opentelemetry::proto::collector::trace::v1::ExportTracePartialSuccess* released = _impl_.partial_success_;
  _impl_.partial_success_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArena() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArena() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::opentelemetry::proto::collector::trace::v1::ExportTracePartialSuccess* ExportTraceServiceResponse::unsafe_arena_release_partial_success() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse.partial_success)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::opentelemetry::proto::collector::trace::v1::ExportTracePartialSuccess* temp = _impl_.partial_success_;
  _impl_.partial_success_ = nullptr;
  return temp;
}
inline ::opentelemetry::proto::collector::trace::v1::ExportTracePartialSuccess* ExportTraceServiceResponse::_internal_mutable_partial_success() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (_impl_.partial_success_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::opentelemetry::proto::collector::trace::v1::ExportTracePartialSuccess>(GetArena());
    _impl_.partial_success_ = reinterpret_cast<::opentelemetry::proto::collector::trace::v1::ExportTracePartialSuccess*>(p);
  }
  return _impl_.partial_success_;
}
inline ::opentelemetry::proto::collector::trace::v1::ExportTracePartialSuccess* ExportTraceServiceResponse::mutable_partial_success() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::opentelemetry::proto::collector::trace::v1::ExportTracePartialSuccess* _msg = _internal_mutable_partial_success();
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse.partial_success)
  return _msg;
}
inline void ExportTraceServiceResponse::set_allocated_partial_success(::opentelemetry::proto::collector::trace::v1::ExportTracePartialSuccess* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete (_impl_.partial_success_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.partial_success_ = reinterpret_cast<::opentelemetry::proto::collector::trace::v1::ExportTracePartialSuccess*>(value);
  // @@protoc_insertion_point(field_set_allocated:opentelemetry.proto.collector.trace.v1.ExportTraceServiceResponse.partial_success)
}

// -------------------------------------------------------------------

// ExportTracePartialSuccess

// int64 rejected_spans = 1;
inline void ExportTracePartialSuccess::clear_rejected_spans() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.rejected_spans_ = ::int64_t{0};
}
inline ::int64_t ExportTracePartialSuccess::rejected_spans() const {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.collector.trace.v1.ExportTracePartialSuccess.rejected_spans)
  return _internal_rejected_spans();
}
inline void ExportTracePartialSuccess::set_rejected_spans(::int64_t value) {
  _internal_set_rejected_spans(value);
  // @@protoc_insertion_point(field_set:opentelemetry.proto.collector.trace.v1.ExportTracePartialSuccess.rejected_spans)
}
inline ::int64_t ExportTracePartialSuccess::_internal_rejected_spans() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.rejected_spans_;
}
inline void ExportTracePartialSuccess::_internal_set_rejected_spans(::int64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.rejected_spans_ = value;
}

// string error_message = 2;
inline void ExportTracePartialSuccess::clear_error_message() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.error_message_.ClearToEmpty();
}
inline const std::string& ExportTracePartialSuccess::error_message() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:opentelemetry.proto.collector.trace.v1.ExportTracePartialSuccess.error_message)
  return _internal_error_message();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void ExportTracePartialSuccess::set_error_message(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.error_message_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:opentelemetry.proto.collector.trace.v1.ExportTracePartialSuccess.error_message)
}
inline std::string* ExportTracePartialSuccess::mutable_error_message() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_error_message();
  // @@protoc_insertion_point(field_mutable:opentelemetry.proto.collector.trace.v1.ExportTracePartialSuccess.error_message)
  return _s;
}
inline const std::string& ExportTracePartialSuccess::_internal_error_message() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.error_message_.Get();
}
inline void ExportTracePartialSuccess::_internal_set_error_message(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.error_message_.Set(value, GetArena());
}
inline std::string* ExportTracePartialSuccess::_internal_mutable_error_message() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _impl_.error_message_.Mutable( GetArena());
}
inline std::string* ExportTracePartialSuccess::release_error_message() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:opentelemetry.proto.collector.trace.v1.ExportTracePartialSuccess.error_message)
  return _impl_.error_message_.Release();
}
inline void ExportTracePartialSuccess::set_allocated_error_message(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.error_message_.SetAllocated(value, GetArena());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.error_message_.IsDefault()) {
          _impl_.error_message_.Set("", GetArena());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:opentelemetry.proto.collector.trace.v1.ExportTracePartialSuccess.error_message)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace trace
}  // namespace collector
}  // namespace proto
}  // namespace opentelemetry


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_opentelemetry_2fproto_2fcollector_2ftrace_2fv1_2ftrace_5fservice_2eproto_2epb_2eh
