// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: opentelemetry/proto/profiles/v1development/profiles.proto

#ifndef GRPC_MOCK_opentelemetry_2fproto_2fprofiles_2fv1development_2fprofiles_2eproto__INCLUDED
#define GRPC_MOCK_opentelemetry_2fproto_2fprofiles_2fv1development_2fprofiles_2eproto__INCLUDED

#include "opentelemetry/proto/profiles/v1development/profiles.pb.h"
#include "opentelemetry/proto/profiles/v1development/profiles.grpc.pb.h"

#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/sync_stream.h>
#include <gmock/gmock.h>
namespace opentelemetry {
namespace proto {
namespace profiles {
namespace v1development {

}  // namespace v1development
}  // namespace profiles
}  // namespace proto
}  // namespace opentelemetry


#endif  // GRPC_MOCK_opentelemetry_2fproto_2fprofiles_2fv1development_2fprofiles_2eproto__INCLUDED
